### ISSUE TITLE
dependabot is trying to help but we aren't doing anything

### ISSUE THREAD

**Issue by SapphireDisD** [RanTodd-Team/RanTodd#66]
### Describe the bug

dependabot, the dependency update bot, is suggesting a lot of changes, but we are just ignoring them (and we aren't updating the bot in any way!).

### To reproduce

Go to "Pull requests".

### Expected behavior

Maintainers accepting/declining these changes (and also them working in other bot aspects).
Archiving the project may also be another option.

### Code of Conduct

- [X] I agree to follow with the Code of Conduct.

**Comment by itsWindows11** [comment]
You have 3 options:

1. Remove dependabot entirely
2. Disable pull request notifications
3. Archive the project (well that's mentioned but I don't really recommend it at the time being)

**Comment by SapphireDisD** [comment]
Honestly, the project seems abandoned.
dependabot is useful, it's just that we aren't doing anything.

**Comment by itsWindows11** [comment]
> Honestly, the project seems abandoned. dependabot is useful, it's just that we aren't doing anything.

Then that leaves option 2 and 3, or we can just review these and test.

**Comment by SapphireDisD** [comment]
We have to discuss this with Dongle and maybe ask our few users.

**Comment by SapphireDisD** [comment]
If we have any...
